services:
  web:
    build:
      context: .
    command: /entrypoint.sh
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DB_HOST: db
      FIXTURE_FILE: /app/fixtures/export_data_v1_2.json
      DJANGO_RUNNING_IN_DOCKER: "true"
#      RABBITMQ_SERVER: rabbit
#    user: "${UID:-1000}:${GID:-1000}"
    depends_on:
      - rabbitmq
    networks:
      - main


  # RabbitMQ - queue
  rabbitmq:
    restart: always
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"



  # Celery worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A lmt_toolkit_analysis worker -l info -P solo
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - web
    networks:
      - main


  frontend:
    build: ../nuxt-api
    command: /entrypoint.sh
    volumes:
      - ../nuxt-api:/app
#      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - web
#    user: "${UID:-1000}:${GID:-1000}"

networks:
  main:
