services:
  web:
    build:
      context: .
    image: lmt_toolkit_analysis_web
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "8000:8000"
    # env_file:
    #   - .env
    environment:
      DB_HOST: db
      FIXTURE_FILE: /app/fixtures/export_data_v1_2.json
      DJANGO_RUNNING_IN_DOCKER: "true"
      CELERY_BROKER_URL: amqp://guest:guest@rabbit:5672//
      SERVICE_ROLE: web
#      RABBITMQ_SERVER: rabbit
#    user: "${UID:-1000}:${GID:-1000}"
    depends_on:
      - rabbitmq


  # RabbitMQ - queue
  rabbitmq:
    restart: always
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"



  frontend:
    build: ../nuxt-api
    volumes:
      - ../nuxt-api:/app
      - frontend_node_modules:/app/node_modules
#      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - web
#    user: "${UID:-1000}:${GID:-1000}"

  # RabbitMQ - queue
  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  # Celery worker
  worker:
    image: lmt_toolkit_analysis_web
    volumes:
      - .:/app
    depends_on:
      - rabbit
      - web
    environment:
      CELERY_BROKER_URL: amqp://guest:guest@rabbit:5672//
      SERVICE_ROLE: worker

networks:
  default:
    name: lmt_toolkit_analysis_network

volumes:
  frontend_node_modules:
