# Generated by Django 4.0.2 on 2022-11-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmttoolkitanalysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='tmax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='tmin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='unitMaxT',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='unitMinT',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
