# Generated by Django 4.0.2 on 2023-02-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmttoolkitanalysis', '0003_file_deletefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='sqlite',
            field=models.FileField(max_length=255, upload_to='.'),
        ),
    ]
