# Generated by Django 4.0.2 on 2023-03-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmttoolkitanalysis', '0004_alter_file_sqlite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lmt_toolkit_version', models.CharField(max_length=255)),
                ('lmt_toolkit_version_link', models.CharField(blank=True, max_length=255, null=True)),
                ('lmt_toolkit_version_date', models.DateField()),
                ('lmt_toolkit_version_changes', models.TextField(blank=True, null=True)),
                ('lmt_analysis_version', models.CharField(blank=True, max_length=255, null=True)),
                ('lmt_analysis_version_changes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versions',
            },
        ),
    ]
