# Generated by Django 4.0.2 on 2023-03-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmttoolkitanalysis', '0006_version_lmt_analysis_version_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('representation', models.ImageField(upload_to='./img/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
