# Generated by Django 4.0.2 on 2023-03-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmttoolkitanalysis', '0007_eventdocumentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdocumentation',
            name='representation',
            field=models.ImageField(null=True, upload_to='./img/'),
        ),
    ]
