# Generated by Django 4.0.2 on 2023-04-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmttoolkitanalysis', '0008_alter_eventdocumentation_representation'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='rebuild',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
