# Generated by Django 4.0.2 on 2023-04-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmttoolkitanalysis', '0009_file_rebuild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='rebuild',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
